"""Relationship editing round trip against isolated sample data."""
exec(open('tests/ui/helpers.py').read())
new_tab(base+'/?mock=1#/leads'); wait_for_load(); settle()
js('openDetail(S.rows[0].id)'); settle()
click_node('button','Worked with relationship')
click_node('button','Friend relationship')
click_node('button','Close')
click_node('button','Spoke before')
js('refreshPerson(S.person.id)'); settle()
check('Readback keeps relationship familiarity and conversation', 'S.person.relationships.includes("friend") && S.person.relationships.includes("worked_with") && S.person.familiarity === "close" && S.person.status === "spoke_before"')
click_node('button','Client relationship')
click_node('button','Worked with relationship')
check('Worked with can clear implied client', '!S.person.relationships.includes("worked_with") && !S.person.relationships.includes("client") && S.person.relationships.includes("friend")')
click_node('button','Close')
check('Familiarity clears', 'S.person.familiarity === null')
check('Friend projects as manual tag', 'S.person.tags.some(t => t.tag === "Friend" && t.source === "manual")')
print(checks)
