"""Regression checks from the 30-reviewer polish round, using sample data only."""
exec(open('tests/ui/helpers.py').read())

new_tab('about:blank')
cdp('Page.addScriptToEvaluateOnNewDocument', source='window.uiErrors=[]; window.addEventListener("error",e=>uiErrors.push(e.message)); window.addEventListener("unhandledrejection",e=>uiErrors.push(String(e.reason)));')
cdp('Emulation.setDeviceMetricsOverride', width=1440, height=1000, deviceScaleFactor=1, mobile=False)
goto_url(base + '/?mock=1&refinements=1')
wait_for_load()
settle()
try:
    click_node('link', 'Leads')
    js('document.querySelector(".lead-open").focus()')
    key('Enter', 'Enter', '\r')
    js('document.querySelector("#detail [data-s=interested]").focus()')
    key('Enter', 'Enter', '\r')
    check('Lead status change preserves button focus', 'document.activeElement.dataset.s === "interested"')
    key('Escape', 'Escape')
    check('Status change still returns focus to the lead', 'document.activeElement.matches(".lead-open")')
    key('x', 'KeyX', 'x')
    js('document.querySelector("#bk-add").focus()')
    key('Escape', 'Escape')
    check('Bulk Escape clears selection and returns to lead', 'S.pick.size === 0 && document.activeElement.matches(".lead-open")')
    key('x', 'KeyX', 'x')
    js('window.beforeHelp=JSON.stringify({rows:S.rows,pick:[...S.pick],view:S.view,density:document.documentElement.dataset.density})')
    key('?', 'Slash', '?')
    for value in ['5', 'm', 'x', 'j', 'c', 'd', 'g', 's', 'Enter', ' ']:
        key(value)
    check('Help blocks background edits and navigation', '!document.querySelector("#help").hidden && beforeHelp === JSON.stringify({rows:S.rows,pick:[...S.pick],view:S.view,density:document.documentElement.dataset.density})')
    key('Escape', 'Escape')
    check('Help dismissal restores its opener', 'document.activeElement.matches(".lead-open")')
    key('x', 'KeyX', 'x')

    js('document.querySelector("#filters [data-tier=hot]").focus()')
    key('Enter', 'Enter', '\r')
    check('Filter focus survives result and facet updates', 'document.activeElement.dataset.tier === "hot" && S.f.tier === "hot"')
    click_node('button', 'Clear')
    click_node('button', 'Save view')
    cdp('Input.insertText', text='Keep my draft')
    js('window.savedPost=api.post; api.post=(url,body)=>url === "/api/views" ? Promise.reject(new Error("Injected save failure")) : savedPost.call(api,url,body)')
    key('Enter', 'Enter', '\r')
    check('Failed saved view retains name and truthful feedback', 'document.querySelector("#v-name")?.value === "Keep my draft" && document.querySelector("#toast").textContent === "Could not save view"')
    js('api.post=savedPost')
    key('Escape', 'Escape')

    # Failure injection is confined to this sample-data tab.
    js('window.savedFetchLeads=fetchLeads; window.pageAttempts=0; fetchLeads=async()=>{pageAttempts++;throw new Error("Injected page failure")}; S.done=false; S.error=false; loadMore()')
    settle()
    js('document.querySelector("#scroll").scrollTop=document.querySelector("#scroll").scrollHeight')
    settle()
    check('Failed pagination keeps rows and waits for explicit retry', 'pageAttempts === 1 && S.rows.length > 0 && !!document.querySelector("#retry-more")')
    js('fetchLeads=savedFetchLeads')
    click_node('button', 'Retry')
    check('Pagination retry recovers', '!S.error && !document.querySelector("#retry-more")')
    js('document.querySelector("#scroll").scrollTop=1200')
    settle()
    before_position = js('document.querySelector("#scroll").scrollTop / rowH()')
    js('document.activeElement.blur()')
    key('d', 'KeyD', 'd')
    check('Density retains the visible lead and fractional position', f'Math.abs(document.querySelector("#scroll").scrollTop / rowH() - {before_position}) < .02')
    js('window.anchorId=S.rows[2].id; S.anchor=2; S.cur=1; window.reordered=[S.rows[2],S.rows[0],S.rows[1],...S.rows.slice(3)]; fetchLeads=async()=>({total:reordered.length,rows:reordered}); resetLeads(true)')
    settle()
    check('Refresh retains the range anchor identity', 'S.rows[S.anchor]?.id === anchorId')
    js('fetchLeads=savedFetchLeads; resetLeads()')
    settle()
    for width in [1280, 1024, 901]:
        cdp('Emulation.setDeviceMetricsOverride', width=width, height=1000, deviceScaleFactor=1, mobile=False)
        js('if(!S.side) toggleSide(); document.querySelector(".lead-open").focus()')
        key('Enter', 'Enter', '\r')
        check(f'Open details {width}: toolbar controls stay inside the lead pane', '[...document.querySelectorAll(".qbar > :not([hidden])")].every(e=>{const b=e.getBoundingClientRect(),p=e.closest(".pane").getBoundingClientRect();return b.left>=p.left-1 && b.right<=p.right+1})')
        js('S.person.bio="https://example.test/"+"long".repeat(100); renderDetail()')
        check(f'Open details {width}: unbroken bio stays contained', 'document.querySelector("#detail").scrollWidth <= document.querySelector("#detail").clientWidth')
        key('Escape', 'Escape')
    cdp('Emulation.setDeviceMetricsOverride', width=320, height=844, deviceScaleFactor=1, mobile=True)
    check('Phone navigation has 44px touch targets', '[...document.querySelectorAll(".tabs a")].every(e=>e.getBoundingClientRect().height>=44 && e.getBoundingClientRect().width>=44)')
    js('document.querySelector(".fl-ctl-summary").focus()')
    key('Enter', 'Enter', '\r')
    click_node('button', 'Pause collect lists')
    check('320px resumed-state controls fit each card', '[...document.querySelectorAll(".fl-ctl-pill button")].every(e=>e.getBoundingClientRect().right<=e.parentElement.getBoundingClientRect().right) && document.documentElement.scrollWidth<=innerWidth')
    click_node('button', 'Resume collect lists')
    shot('leads-dark-320')

    cdp('Emulation.setDeviceMetricsOverride', width=1440, height=1000, deviceScaleFactor=1, mobile=False)
    click_node('link', 'Tags')
    js('document.querySelector("#tg-body [data-ck]").focus()')
    key(' ', 'Space', ' ')
    check('Tag checkbox retains focus and announces selection', 'document.activeElement.matches("#tg-body [data-ck]") && document.activeElement.getAttribute("aria-checked") === "true" && document.querySelector("#tg-all").getAttribute("aria-checked") === "mixed"')
    js('document.querySelector("#tg-q").focus()')
    cdp('Input.insertText', text='no-such-tag-polish-check')
    settle()
    check('Tag search explains no matches', 'document.querySelector("#view-tags").textContent.includes("No matching tags.")')

    click_node('link', 'Qualification')
    check('Qualification score appears once in its heading', 'document.querySelector(".ql-score").querySelectorAll("b").length === 1')
    js('document.querySelector("#ql-q").focus()')
    cdp('Input.insertText', text='no-such-qual-polish-check')
    settle()
    check('Qualification search explains no matches', 'document.querySelector(".ql-empty").textContent === "No people match this search."')
    key('a', 'KeyA') if False else None
    js('document.querySelector("#ql-q").value=""; Q.q=""; Q.load()')
    settle()
    js('window.deepId=Q.rows.find(r=>r.website).id; document.querySelector(`[data-deep="${deepId}"]`).focus()')
    key('Enter', 'Enter', '\r')
    check('Dig deeper retains focus and names the website platform', 'document.activeElement.dataset.deep === String(deepId) && document.querySelector(`[data-id="${deepId}"] .ql-site`).textContent.includes("Built on Shopify")')

    click_node('link', 'Scraper')
    js('document.querySelector("#lists-f [data-v=active]").focus()')
    time.sleep(1.2)
    check('Scraper polling retains filter focus', 'document.activeElement.dataset.v === "active" && document.activeElement.closest("#lists-f") !== null')
    click_node('link', 'Accounts')
    check('Account roles expose active state', '[...document.querySelectorAll("[data-role], [data-main]")].every(e=>e.getAttribute("aria-pressed") === String(e.classList.contains("on")))')
    js('document.querySelector("[data-rename]").focus()')
    key('Enter', 'Enter', '\r')
    cdp('Input.insertText', text='Retain this account label')
    js('window.savedPost=api.post; api.post=(url,body)=>url.startsWith("/api/accounts/") ? Promise.reject(new Error("Injected save failure")) : savedPost.call(api,url,body)')
    key('Enter', 'Enter', '\r')
    check('Failed account rename retains its draft', 'document.querySelector("#acc-label")?.value === "Retain this account label" && document.activeElement.id === "acc-label"')
    js('api.post=savedPost')
    key('Escape', 'Escape')
    click_node('link', 'Settings')
    cdp('Emulation.setDeviceMetricsOverride', width=320, height=844, deviceScaleFactor=1, mobile=True)
    settle()
    check('320px: all checking modes fit within their card with readable touch targets', '(()=>{const c=document.querySelector("#set-mode").closest(".card").getBoundingClientRect();return [...document.querySelectorAll("#set-mode button")].every(e=>{const b=e.getBoundingClientRect();return b.left>=c.left && b.right<=Math.min(c.right,innerWidth) && b.height>=40 && e.scrollWidth<=e.clientWidth})})()')
    shot('settings-mode-320')
    cdp('Emulation.setDeviceMetricsOverride', width=1440, height=1000, deviceScaleFactor=1, mobile=False)
    settle()
    check('Settings switches announce their state', '["set-q-auto"].every(id=>{const e=document.getElementById(id);return e.getAttribute("aria-pressed") === String(e.classList.contains("on"))})')
    js('window.savedGet=api.get; api.get=(url)=>url==="/api/llm/health" ? Promise.reject(new Error("Injected health failure")) : savedGet.call(api,url); checkHealth()')
    settle()
    check('Failed service check stops saying Checking', 'document.querySelector("#set-svc").textContent.includes("Could not check") && !document.querySelector("#set-svc").textContent.includes("Checking")')
    js('api.get=savedGet')
    click_node('link', 'Map')
    click_node('button', 'Labels')
    check('Map labels announce state', 'document.querySelector("#map-labels").getAttribute("aria-pressed") === String(M.labels)')
    click_node('button', 'All')
    check('Map scope announces selection', 'document.querySelector("#map-scope [data-v=all]").getAttribute("aria-pressed") === "true" && document.querySelector("#map-scope [data-v=leads]").getAttribute("aria-pressed") === "false"')
    check('No uncaught errors in refinement interactions', 'window.uiErrors.length === 0')
finally:
    (out / 'refinements.json').write_text(json.dumps(checks, indent=2))
    print(json.dumps({'passed': sum(c['passed'] for c in checks), 'total': len(checks), 'output': str(out)}))
