"""Settings, navigation, and configured-mode QA. Isolated browser and mock only."""
exec(open('tests/ui/helpers.py').read())
try:
    new_tab(base + '/?mock=1&layout_check=1#/settings')
    wait_for_load()
    settle()
    check('Mock settings is active', 'location.search.includes("mock=1") && S.view==="settings"')
    check('Six everyday destinations remain direct links', 'document.querySelectorAll(".tabs a[data-view]").length===6 && !document.querySelector(".tabs details")')
    check('Appearance has one location and setup has no nested disclosures', '!document.querySelector("#theme-btn,#density-btn,#view-settings details details") && !!document.querySelector("#set-theme") && !!document.querySelector("#set-density")')
    for width in [1440, 390, 320]:
        cdp('Emulation.setDeviceMetricsOverride', width=width, height=1000, deviceScaleFactor=1, mobile=width<500)
        settle()
        check(f'{width}: mode choices fit their card', '[...document.querySelectorAll("#set-mode button")].every(e=>{const b=e.getBoundingClientRect(),p=e.closest(".card").getBoundingClientRect();return b.left>=p.left && b.right<=p.right && e.scrollWidth<=e.clientWidth})')
        check(f'{width}: navigation fits with touch targets', '[...document.querySelectorAll(".tabs a")].every(e=>{const b=e.getBoundingClientRect();return b.right<=innerWidth && b.width>=40 && (innerWidth>760 || b.height>=44)})')
        shot(f'settings-{width}')
        js('document.querySelector("#external-setup summary").focus()')
        key('Enter', 'Enter', '\r')
        check(f'{width}: external setup opens using keyboard', 'document.querySelector("#external-setup").open')
        check(f'{width}: expanded setup contains horizontal overflow', 'document.documentElement.scrollWidth<=innerWidth && document.querySelector("#view-settings .scr").scrollWidth<=document.querySelector("#view-settings .scr").clientWidth')
        js('document.querySelector("#external-setup summary").focus()')
        key('Enter', 'Enter', '\r')
    click_node('button', 'Rules only')
    check('Rules mode saves without enabling external AI', 'S.sc.local_laya===false && S.sc.qualify===false')
    click_node('button', 'Local models + rules')
    check('Local mode saves without enabling external AI', 'S.sc.local_laya===true && S.sc.qualify===false')
    click_node('button', 'Light')
    check('Theme control remains usable from Settings', 'document.documentElement.dataset.theme==="light"')
    shot('settings-light-320')
    click_node('link', 'Accounts')
    check('Account health and collection route remain visible', 'document.querySelectorAll("#acc-list [data-lane]").length>0 && document.querySelector(".account-collection-link").getBoundingClientRect().width>0')
    check('Startup action names only local services', 'document.querySelector("#acc-start").textContent==="Start local models"')
    shot('accounts-320')
    click_node('link', 'Collection progress')
    check('Collection remains reachable without a sidebar item', 'S.view==="scraper"')
finally:
    (out / 'settings-layout.json').write_text(json.dumps(checks, indent=2))
    print(json.dumps({'passed': sum(c['passed'] for c in checks), 'total': len(checks), 'output': str(out)}))
