"""Daily lead workflow: cursor, status menu, undo, detail lifecycle. Isolated ?mock=1 data only."""
exec(open('tests/ui/helpers.py').read())
import os
W = int(os.environ.get('W', '1440'))
new_tab(base + '/?mock=1'); wait_for_load(); js('localStorage.clear(); sessionStorage.clear()'); settle()
cdp('Emulation.setDeviceMetricsOverride', width=W, height=900 if W > 500 else 844, deviceScaleFactor=1, mobile=W < 500)
js('location.reload()'); wait_for_load(); time.sleep(1.5)
tag = f'-{W}'
if W > 500:
    check('First lead is the cursor on load', 'S.cur === 0 && !!document.querySelector("#rows .row.cur")')
    key('s', 'KeyS', 's')
    check('s opens the status menu', '!!document.querySelector("#status-menu")')
    shot('status-menu' + tag)
    key('1', 'Digit1', '1')
    check('Choosing a status closes the menu and shows Undo', '!document.querySelector("#status-menu") && S.rows[0].status === "interested" && !!document.querySelector("#undo")')
    shot('undo' + tag)
    js('document.querySelector("#undo").click()'); settle()
    check('Undo restores the previous status', '!S.rows[0].status')
    key('j', 'KeyJ', 'j')
    check('j moves the cursor', 'S.cur === 1')
    key('Enter', 'Enter', '\r'); time.sleep(.8)
    check('Enter opens detail', 'S.open === S.rows[1].id')
    js('document.activeElement.blur()')
    key('n', 'KeyN', 'n')
    check('n focuses the note', 'document.activeElement.id === "note"')
    js('document.activeElement.blur()')
    shot('detail' + tag)
    key('Escape', 'Escape')
    check('Esc closes detail', '!S.open')
    key('Enter', 'Enter', '\r'); time.sleep(.6)
    js('location.hash = "#/qual"'); time.sleep(.6)
    check('Detail closes when leaving Leads', '!S.open && !S.person')
    js('location.hash = "#/leads"'); time.sleep(.6)
    check('Detail stays closed on return', '!S.open && document.querySelector("#detail").hidden')
    js('S.f.status = "spoke_before"; filtersChanged()'); time.sleep(1)
    if js('S.rows.length'): js('S.f.q = "zzzz-nobody"; filtersChanged()'); time.sleep(1)
    shot('empty' + tag)
else:
    js('document.querySelector(".lead-open").click()'); time.sleep(1)
    check('Mobile detail has next/previous', '!!document.querySelector("#d-next")')
    shot('detail' + tag)
    js('document.querySelector("#d-next").click()'); time.sleep(.8)
    check('Next lead opens the following person', 'S.open === S.rows[1].id')
    js('location.hash = "#/qual"'); time.sleep(.6)
    check('Detail closes when navigating on phone', '!S.open')
    js('location.hash = "#/leads"'); time.sleep(.6)
    shot('list' + tag)
import json
(out / f'checks{tag}.json').write_text(json.dumps(checks, indent=1))
print('ok', len(checks))
